server:
  port: 8080
spring:
  redis:
    host: 192.168.117.128
    port: 6379
    database: 0
    password: 123456
  cache:
    redis:
      time-to-live: 1800000
  application:
    name: project_springboot
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.1.103:3306/db2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    properties:
      mail:
        smtp:
          ssl:
            enable: ture
          suth: ture
          starttls:
            enable: true
            requestd: ture
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    post: 4655
    protocol: smtp
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID



reggie:
  path: D:\Project\project_springboot\img\
